[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v -s
pythonpath = .
norecursedirs = workspace .* build dist CVS _darcs {arch} *.egg venv
