title: QUASAR
version: 0.4.0
description: Documentation for QUASAR, the Universal Autonomous System for Atomistic Research.
url: https://fengxuyy.github.io
baseurl: /QUASAR
markdown: kramdown
highlighter: rouge
permalink: pretty
kramdown:
  input: GFM
defaults:
  - scope:
      path: ""
    values:
      layout: default
repository_url: https://github.com/fengxuyy/QUASAR
